### PR TITLE
Private GKE nodes

### LINKED ISSUE #29: Columbia GKE VMs can't have external IPs. Use NAT instead?
In working on #19, I ran into the following error upon running `make deploy` (pretty sure it's triggered by [this line](https://github.com/pangeo-forge/pangeo-forge-gcs-bakery/blob/8cb9c6dcf8a49d42fddb31b51f9d5be45dbd945a/scripts/deploy.sh#L97)):

```
│ Error: Error waiting for creating GKE cluster: 
│       (1) Not all instances running in IGM after 27.91542561s. Expected 1, running 0, transitioning 1. Current errors: [CONDITION_NOT_MET]: Instance 'gke-pfcsb-cluster-default-pool-83972429-mhbp' creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 13667658525. Add instance projects/pangeo-forge-4967/zones/us-central1-f/instances/gke-pfcsb-cluster-default-pool-83972429-mhbp to the constraint to use external IP with it
│       (2) Not all instances running in IGM after 29.8823857s. Expected 1, running 0, transitioning 1. Current errors: [CONDITION_NOT_MET]: Instance 'gke-pfcsb-cluster-default-pool-5f0b4f10-v4xk' creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 13667658525. Add instance projects/pangeo-forge-4967/zones/us-central1-a/instances/gke-pfcsb-cluster-default-pool-5f0b4f10-v4xk to the constraint to use external IP with it
│       (3) Not all instances running in IGM after 33.618018184s. Expected 1, running 0, transitioning 1. Current errors: [CONDITION_NOT_MET]: Instance 'gke-pfcsb-cluster-default-pool-ce7e23ec-87w8' creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 13667658525. Add instance projects/pangeo-forge-4967/zones/us-central1-b/instances/gke-pfcsb-cluster-default-pool-ce7e23ec-87w8 to the constraint to use external IP with it.
│
│   with google_container_cluster.primary,
│   on cluster.tf line 9, in resource "google_container_cluster" "primary":
│    9: resource "google_container_cluster" "primary" {
```
I'll confess that I initially thought (and my initially I mean for the past 3 hours or so 🤦) that this had something to do with my laptop's IP address, and tried various ill-conceived workarounds for that, including running `make deploy` from GCP's in-browser shell; using GCP's graphical in-browser GKE cluster creation tool; and re-trying  locally with Columbia's VPN enabled. All methods produced the same error.

I now see (thanks, [reddit](https://www.reddit.com/r/googlecloud/comments/m0wosp/why_is_it_the_default_to_have_external_ip/)) that this is a matter of the networking config for the VMs themselves, not the IP address from which their creation is requested. I have checked with @rabernat, who reports that changing `constraints/compute.vmExternalIpAccess` settings will be a non-starter for Columbia. Therefore, I believe we'll need an alternative wherein VMs do not use external IPs.

@tracetechnical @sharkinsspatial am I correct in assuming that [network address translation (NAT)](https://cloud.google.com/nat/docs/overview) is the way forward with this? If so, what are next steps for re-configuring our `terraform` to use this approach? If not, what other options do we have?

### PR DESCRIPTION
**Pull request by cisaacstern**
Closes #29

This PR is mostly a direct copy of https://github.com/2i2c-org/infrastructure/pull/538 which ... totally works! :tada: Here is a snapshot of the GCS console with three running private nodes, created by calling `make deploy` from this branch:

Screen Shot 2022-01-31 at 11 32 38 PM

@sgibson, first I cannot thank you enough for this incredibly helpful reference. Second, I wanted to ask, is there a reason why you assigned various values to empty `[]` or `{}` as part of the above-linked PR? (e.g., [here](https://github.com/2i2c-org/infrastructure/pull/538/files#diff-a2cc5077965b9ba44025999450c23cb2b6d6265f69ddf2427be415112cd2a37bR11-R12), [here](https://github.com/2i2c-org/infrastructure/pull/538/files#diff-d5dbe48caae716d30dc79c679cc957f6487918b50410d2d20b1cba2e3e0f1038R88-R89), and [here](https://github.com/2i2c-org/infrastructure/pull/538/files#diff-d5dbe48caae716d30dc79c679cc957f6487918b50410d2d20b1cba2e3e0f1038R130-R131)) That is, is this just general good practice, or is it something specifically tied to the private GKE nodes? I haven't included those assignments here, and terraform seems to work without them, but it's quite possible I'm overlooking something.

@rabernat @tracetechnical @sharkinsspatial, we don't have comprehensive tests for this infrastructure (perhaps that's not even feasible), so I'm basing my assessment that this works based on the fact that, by including this additional config, I am now able to run `make deploy` and create a GKE cluster without erroring out. Beyond that, I did start to explore the `make test-flow` command described in the README, and it did appear to execute in some form, though evaluating its outcome felt outside the scope of this PR, which is really just about creating the private nodes.

> Note also I did also need to change 
https://github.com/pangeo-forge/pangeo-forge-gcs-bakery/blob/bd52859e45e33f6bc90057b2e7eaad768041c529/terraform/storage.tf#L18
to my GCS user email address to get `make deploy` to work. AFAICT, that is not documented in the README, but we can address it in a separate PR, as it's not directly related to the private nodes work.

### CODE REVIEW

File: scripts/deploy.sh [hunk 1]
```diff
@@ -78,6 +78,13 @@ else
   echo "CLUSTER_REGION is set to ${CLUSTER_REGION}"
 fi
 
+if [ -z "${ENABLE_PRIVATE_CLUSTER}" ]; then
```
Comment (tracetechnical) [inline scripts/deploy.sh:81]: We probably ought to trap non boolean values near here.

File: terraform/cluster.tf [hunk 2]
```diff
@@ -25,6 +25,37 @@ resource "google_container_cluster" "primary" {
       ip_allocation_policy
     ]
   }
+
+  /**
```
Comment (tracetechnical) [inline terraform/cluster.tf:29]: To keep the code clean, this should be documented in the README.

Comment (tracetechnical) [reply terraform/cluster.tf:29]: Comments in code tend to go stale or worse not reflect the actual code. Where the code isn't self descriptive, we should fall back to documenting it in the relevant readme section.

File: terraform/network.tf [hunk 3]
```diff
@@ -0,0 +1,57 @@
+/**
+* Networking to support private clusters. This config is only deployed when the
+* enable_private_cluster variable is set to true.
```
Comment (tracetechnical) [inline terraform/network.tf:3]: As per other comment re comments in code

File: terraform/network.tf [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+  network = data.google_compute_network.default_network.name
+
+  allow {
+    protocol = "tcp"
+    ports    = ["22"]
+  }
+
+  // This range contains all IP addresses that IAP uses for TCP forwarding.
+  // https://cloud.google.com/iap/docs/using-tcp-forwarding
+  source_ranges = ["35.235.240.0/20"]
```
Comment (tracetechnical) [inline terraform/network.tf:32]: This should be fed in as a variable with a default, rather than hardcoded.

File: terraform/network.tf [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+  count = var.enable_private_cluster ? 1 : 0
+
+  name                               = "${var.project_name}-router-nat"
+  project                            = var.project_name
+  region                             = var.cluster_region
+  router                             = google_compute_router.router[0].name
+  nat_ip_allocate_option             = "AUTO_ONLY"
+  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
+
+  // Set these values explicitly so they don't "change outside terraform"
```
Comment (tracetechnical) [inline terraform/network.tf:54]: See above comments about comments

**Review by tracetechnical — CHANGES_REQUESTED** [review]

File: terraform/cluster.tf (hunk 2 above)
Comment (rabernat) [reply terraform/cluster.tf:29]: Trace, really appreciate your review here! 🙏 

Just so I understand, are you really advocating that ALL inline code comments are a practice to avoid? You yourself have left inline comments in this [same file](https://github.com/pangeo-forge/pangeo-forge-gcs-bakery/blame/main/terraform/cluster.tf#L51). I don't see how these are qualitatively different.

Whether code is self-descriptive depends a lot on the audience. Charles and I are completely new to terraform, so some inline comments can be really helpful in understanding what a particular code block is for. I agree there is a maintenance cost to adding comments.

Maybe rather than saying,  "let's avoid all inline comments," we could ask, "are these specific notes better placed inline vs. in the README?"

Comment (tracetechnical) [reply terraform/cluster.tf:29]: This is a fair counter-point. I need to look into more around best practises when it comes to Terraform and code comments, but I have always been told "inline comments bad" across the languages I have written in several companies.

Unfortunately, the comment which was in that file was as a result of a shameless copy-pasta on my part, rather than an intentional "This comment needs to be here to inform people". And this particular one should also be migrated to the README, which I will take an action point to do.

I'd prefer to retain the reduction of inline comments where possible, and perhaps flesh out the "per file" sections of the readme with references to the codeblocks where these are needed to help newer contributors. 
This has a few benefits:
- Keeping the code uncluttered
- Allowing ease of searching (versus GitHubs code search which is buggy at best)
- Keeping all the information in one place - Making the README the Goto for "How does this thing work"

Comment (tracetechnical) [reply terraform/cluster.tf:29]: WRT the above: it looks like I was thinking of another repo where each file and its purpose was in the README. I will take an action item to get this added to the README for this.

Comment (rabernat) [reply terraform/cluster.tf:29]: Ok great, so it sounds like we have a path forward.
- Let's finish up this review focusing on the actual code and get it merged so Charles can unblock his next steps
- Next you can make a pass through and migrate inline comments into a Readme to suit your style preferences (which are certainly better-informed than ours)

Does that sound oK?

Comment (tracetechnical) [reply terraform/cluster.tf:29]: That sounds spot on. 

The main reason for requesting the changes was to prompt the "Is this something we can do very quickly? If not, then when?" discussion. And I agree that "Soon, but not now" is the right answer. 

If you are happy with the approach RE: explaining each file and its purpose in the readme (plus a section for gotchas maybe?), then that sounds good to me.

**Review by tracetechnical — APPROVED** [review]

File: terraform/network.tf (hunk 3 above)
Comment (tracetechnical) [reply terraform/network.tf:3]: See discussion above

File: terraform/network.tf (hunk 5 above)
Comment (tracetechnical) [reply terraform/network.tf:54]: See discussion above

File: terraform/network.tf (hunk 4 above)
Comment (tracetechnical) [reply terraform/network.tf:32]: Quick one, what is IAP?

File: scripts/deploy.sh (hunk 1 above)
Comment (rabernat) [reply scripts/deploy.sh:81]: We should still do this

File: terraform/network.tf (hunk 4 above)
Comment (rabernat) [reply terraform/network.tf:32]: and we should still do this. No idea about IAP, probably have to ask Yuvi or Sarah.

Comment (tracetechnical) [reply terraform/network.tf:32]: *Note: probably worth adding to the docs how the interaction with IAP works for this usecase
Also, now on the fence RE: putting this in a variable after pondering it some more. 

If this were to be used in another terraform project as a module, it may be more worthwhile, but I think that is unlikely in this case. The only time I can see this being changed is to add other whitelist IPs for on-prem access from static IPs (Non-Columbia usecases)

**Review by tracetechnical — APPROVED** [review]
--

File: terraform/network.tf (hunk 4 above)
Comment (tracetechnical) [reply terraform/network.tf:32]: For the benefit of others having googled it: IAP is Google's Identity Aware Proxy :)

File: scripts/deploy.sh (hunk 1 above)
Comment (tracetechnical) [reply scripts/deploy.sh:81]: I'm wondering if this is a "do it nowwww" thing? as the instructions in env are pretty clear about it being boolean.
I'm on the fence about the "when" of this one.

**Comment by cisaacstern** [comment]
Thanks for the prompt review, @tracetechnical! I started https://github.com/pangeo-forge/pangeo-forge-gcs-bakery/issues/31 to track the point you raised about trapping non-boolean values of `enable_private_cluster`. I'll leave it to you to start any other issues you see fit, including for documentation/comments cleanup, and (if it ultimately seems preferable) variablizing IAP source ranges etc. 

Since I see your ✅ , going to merge now in interest of moving forward with #19. 🚀

**Comment by tracetechnical** [comment]
(I mention Azure specifically as MS seem to absolutely love surprise changes to their terraform providers (non existent fields, undocumented expectations etc).)
